[versions]
kotlin                             = '2.2.21'
firebaseBom                        = "34.5.0"
rustoreBom                         = "2025.11.01"

[libraries]
getkeepsafe-relinker               = "com.getkeepsafe.relinker:relinker:1.4.5"

firebase-bom                       = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
rustore-bom                        = { module = "ru.rustore.sdk:bom", version.ref = "rustoreBom" }
firebase-analytics                 = { module = "com.google.firebase:firebase-analytics" }

admobads                           = "com.google.android.gms:play-services-ads:24.7.0"
google-play-billing                = "com.android.billingclient:billing:7.1.1"
google-play-review                 = "com.google.android.play:review:2.0.2"
google-app-update                  = "com.google.android.play:app-update:2.1.0"

play-services-games                = "com.google.android.gms:play-services-games-v2:21.0.0"
play-services-auth                 = "com.google.android.gms:play-services-auth:21.4.0"
play-appset                        = "com.google.android.gms:play-services-appset:16.1.0"

user_messaging_platform            = "com.google.android.ump:user-messaging-platform:4.0.0"
yandexadssdk                       = "com.yandex.android:mobileads:7.16.1"

rustore-appreview                  = { module = "ru.rustore.sdk:review" }
rustore-appupdate                  = { module = "ru.rustore.sdk:appupdate" }
rustore-billing                    = { module = "ru.rustore.sdk:pay" }

lifecycle-viewmodel-ktx            = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.3"

mytarget-sdk                       = "com.my.target:mytarget-sdk:5.27.1"

[plugins]
android-application                = { id = 'com.android.application', version = '8.13.0' }
google-services                    = { id = 'com.google.gms.google-services', version = '4.4.4' }
kotlin                             = { id = 'org.jetbrains.kotlin.android', version.ref = 'kotlin' }
triplet-play-publisher             = { id = 'com.github.triplet.play', version = '3.12.1' }

[bundles]
yandexads                          = ['yandexadssdk']
rustore-billing                    = ['rustore-billing', 'lifecycle-viewmodel-ktx']